### PR TITLE
Feature: Update Gradle Plugin

### PR DESCRIPTION
**Pull request by SnowVolf**
AGP 8.1
Builds and runs successfully
@TrianguloY

### CODE REVIEW

**Comment by SnowVolf** [comment]
I'm starting to port for new androids

**Comment by TrianguloY** [comment]
Thank you! I see the gradle update is relatively short, but still the effort to actually make it is highly appreciated.
I'm more concerned about the sdk update, keep me updated! 

Note: I'm still not sure how to manage the new updates. Most probably I'll create a branch/tag to keep the currently original state, and continue on master with the proper readme update. Please keep the pr open until then!

**Comment by SnowVolf** [comment]
> Note: I'm still not sure how to manage the new updates. Most probably I'll create a branch/tag to keep the currently original state, and continue on master with the proper readme update. Please keep the pr open until then!

@TrianguloY 
Thank you. Yes. Updating Cradle is a small commit, but it is necessary for further work in modern Android Studio. At work, I'm used to using git flow, I think it will be most convenient. In my personal checklist: 
- Removing the "wear" module (as it out of date). 
- Bumping min sdk to 28 (cutting off old devices). 
- Target SDK 33
- Scoped Storage Support
- Other compatibility bug fixes

**Comment by SnowVolf** [comment]
@TrianguloY please create separate "develop" branch

**Comment by TrianguloY** [comment]
Since I'm not the owner of this repo, and I would like it to be preserved as much as possible, I've though of another alternative:

Keep this repo unmodified (maybe even archived?) and move all development to my own fork. There I can even add collaborators if necessary.
This can even be done as a test, and if successful this repo can be then modified with a link or synced.

On one hand I don't like using my own repo, but on the other I don't want to touch this one without explicit approval from Pierre.

Thoughts?

**Comment by SnowVolf** [comment]
@TrianguloY Ok. I agree with your conclusions. Then it is better to create a develop branch in your repository, and continue development within of the standard git flow

**Comment by SnowVolf** [comment]
@TrianguloY So, I will have to delete my fork, and fork your repository.

**Comment by TrianguloY** [comment]
> @TrianguloY So, I will have to delete my fork, and fork your repository.

No, you should be able to create a PR from your fork into mine. I can do it myself if you prefer.

When you create a PR you can choose the base and head branches, including the repository they are from.

**Comment by TrianguloY** [comment]
The development and 'cleanup' was moved to my fork: https://github.com/TrianguloY/LightningLauncher/tree/developer

**Comment by JardaG** [comment]
> * Scoped Storage Support

Please don't forget for those who use root and LL to script and work with files on different repositories, see my former plugin on ToDo notes to the directory structure, written directly in LL. I miss him a lot now. :(

**Pull request closed without merging**
